### ISSUE TITLE
ESLint: 'it' is not defined. (no-undef)

### ISSUE THREAD

**Issue by liaokaime** [cypress-io/cypress-component-examples#1]
![image](https://user-images.githubusercontent.com/27792976/118346610-5828d380-b56f-11eb-8c33-a07e7e0c30dd.png)

Webstorm told me it, how do I fix it?

**Comment by lmiller1990** [comment]
I am not seeing this error - I am using VS Code, not Webstorm.

You could try adding [eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) and extending your config in `package.json`, perhaps:

```
{
  "extends": [
    "plugin:cypress/recommended"
  ]
}
```

**Comment by liaokaime** [comment]
I fixed this by adding the cypress folder to .eslintignore

**Comment by lmiller1990** [comment]
@liaokaime  I updated my post above after you posted and closed the issue - check that out. You can use `.eslintignore`, but I think we can fix it by extending the `eslintConfig` in `package.json`.
