### ISSUE TITLE
Seems broken

### ISSUE THREAD

**Issue by lambda0xff** [cypress-io/cypress-component-examples#2]
repro steps:
1: download / clone repo
2: cd into the nuxt-vue-2-cypress folder
3: yarn install
4: yarn cypress ct-open

Error message: 
```
Error the plugins file is mising or invalid
...
...

{
  isCypressErr: true,
  type: 'PLUGINS_FILE_ERROR',
  details: "Error: Cannot find module 'webpack-dev-server'\n" +

...
[rest omitted]
```

The `webpack-dev-server` module is correctly installed and is present in the `node_modules` directory

**Comment by ga-devfront** [comment]
Same issue for me, any know how to solve this problem ?

**Comment by lmiller1990** [comment]
I think this is something to do with module resolution. It's working fine for me - I am using `npm`. I found a similar problem (with an unrelated repo) using `yarn`.

What version of `yarn` are you using? What does `yarn --version` print?

**Comment by ajmedeio** [comment]
Same issue for me on npm

**Comment by ajmedeio** [comment]
I ran `npm install --save-dev webpack-dev-server@3` and that at least got cypress to open - currently it's not detecting my spec files though so still troubleshooting.

**Comment by ajmedeio** [comment]
Ayy, got it running - just needed to suffix my spec file with ts instead of js.

**Comment by lmiller1990** [comment]
Are you sure? It should be the other away around - [this config](https://github.com/cypress-io/cypress-component-examples/blob/main/nuxt-vue-2-cypress/cypress.json#L2) is looking for `*.spec.js`:

```json
{
  "testFiles": "**/*.spec.js",
  "componentFolder": "components"
}
```

**Comment by ajmedeio** [comment]
Sorry - I adapted the project to use typescript - so I'm writing the tests in ts as well.
