### ISSUE TITLE
Vite vue can't find tests

### ISSUE THREAD

**Issue by purejgleason** [cypress-io/cypress-component-examples#3]
What I do...

`git clone https://github.com/cypress-io/cypress-component-examples`
`cd cypress-component-examples/vite-vue`
`npm i`
`npx cypress run`

What I would expect...

The example to run

What I get

```
It looks like this is your first time using Cypress: 7.2.0

  ✔  Verified Cypress! /.../Cypress/7.2.0/Cypress.app

Opening Cypress...
Can't run because no spec files were found.

We searched for any files inside of this folder:
/.../cypress-component-examples/vite-vue/cypress/integration
```

I confirmed the spec files are in source

**Comment by lmiller1990** [comment]
Hi! Sorry for the slow reply.

I updated all the dependencies and gave it a try. It's working fine for me. I then realized the problem; documentation isn't good. You need to run `npx cypress open-ct` or `npx cypress run-ct` for component testing. `open` and `run` are for the standard e2e runner.

Can you please give that a try?
