### ISSUE TITLE
vite-vue template not working

### ISSUE THREAD

**Issue by Bassadin** [cypress-io/cypress-component-examples#7]
I tried downloading and starting the vite-vue template because I want to use cypress in my own vite/vue project. However, cypress doesn't find the src/HelloWorld.spec.js files, apparently:

```bash
$ yarn run cypress run
yarn run v1.22.18
warning package.json: No license field
$ E:\Downloads\cypress-component-examples-main\vite-vue\node_modules\.bin\cypress run

Can't run because no spec files were found.

We searched for any files inside of this folder:

E:\Downloads\cypress-component-examples-main\vite-vue\cypress\integration
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Reproductible by just doing
- `yarn`
- `yarn run cypress run`

**Comment by geromegrignon** [comment]
Hi @Bassadin,

As stated in the README file, this project is no longer maintained.
You will find a link to the repo there.

**Comment by Bassadin** [comment]
Thanks for the quick answer!
